import { Geist, Geist_Mono, Poppins } from "next/font/google";
import Head from "next/head";
import "./globals.css";

import Navbar from "@/components/navbar/Navbar";
import FloatingSupportButton from "@/components/button/FabButton";
import Footer from "@/components/footer/Footer";
import ReduxProvider from "../lib/providers/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Smile Home Service",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap everything with ReduxProvider */}
        <ReduxProvider>
          <Head>
            <title>HomeServe | Professional Home Services</title>
            <meta
              name="description"
              content="Book trusted professionals for all your home service needs"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar />
          {children}
          <Footer />
          <FloatingSupportButton />
        </ReduxProvider>
      </body>
    </html>
  );
}
